package com.bitpunchlab.android.pawsgo


enum class AppState {
    NORMAL,
    LOGGED_IN,
    LOGGED_OUT,
    INCORRECT_CREDENTIALS,

    READY_CREATE_USER_AUTH,
    ERROR_CREATE_USER_AUTH,
    READY_CREATE_USER_FIREBASE,
    SUCCESS_CREATED_USER_ACCOUNT,
    ERROR_CREATE_USER_ACCOUNT,

    LOST_DOG_REPORT_SENT_SUCCESS,
    LOST_DOG_REPORT_SENT_ERROR,

    MESSAGE_SENT_SUCCESS,
    MESSAGE_SENT_ERROR,
    RESET
}

